# fly.toml app configuration file generated for open-design-fi on 2026-05-08T03:12:47Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'open-design-fi'
primary_region = 'sin'

[build]

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
